# Introduction to Machine Learning (ML) with Python 01

Here are some preliminary examples in Machine Learning and the basic steps of how to implement training processes.

In the next tutorials, the different kinds of ML models (Supervised/Unsupervised Learning) and the algorithms that are based on will be studied.

A good reference to ML models is the following book:
* [An Introduction to Statistical Learning by James, G., Witten, D., Hastie, T., Tibshirani, R.](https://www.springer.com/gp/book/9781461471370)
* [Amazon link](https://www.amazon.com/Introduction-Statistical-Learning-Applications-Statistics/dp/1461471370)

**Please, check the `ml_map.png` figure, which is a cheat sheet that helps you to decide which Machine Learning process and category to follow based on your data!**

![Machine Learning Map](ml_map.png)

#### Importing libraries

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

* **train_test_split** is used to split the data
* **LinearRegression** is the *Estimator* and **linear_model** is the *family*

In [2]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [3]:
X  # are the actual features

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
list(y)  # y is the actual labels for each of the feature rows

[0, 1, 2, 3, 4]

#### Train/Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)  
# splitting the data: 0.3 means 30% of the whole dataset
X_train

array([[8, 9],
       [2, 3],
       [0, 1]])

In [6]:
X_test

array([[6, 7],
       [4, 5]])

In [7]:
y_train

[4, 1, 0]

In [8]:
y_test

[3, 2]

#### Supervised Learning process! (In Unsupervised Learning, we don't have labels!)

In [9]:
# instatiating the Linear Regression model
model = LinearRegression()

In [10]:
# training/fitting our model on the training data
# We use the model.fit() method --> model.fit(X_train, y_train)
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

* Now the model has been fit and trained on the training data
* The model is ready to predict labels or values on the test set

In [11]:
predictions = model.predict(X_test)

In [12]:
predictions

array([3., 2.])

* We can then evaluate our model by comparing our predictions to the correct values
* The evaluation method depends on what sort of machine learning algorithm we are using (e.g. Regression, Classification, Clustering, etc.)