# Introduction to Machine Learning (ML) with Python 02

Here are some preliminary examples in Machine Learning and the basic steps of how to implement training processes.

In the next tutorials, the different kinds of ML models (Supervised/Unsupervised Learning) and the algorithms that are based on will be studied.

A good reference to ML models is the following book:
* [An Introduction to Statistical Learning by James, G., Witten, D., Hastie, T., Tibshirani, R.](https://www.springer.com/gp/book/9781461471370)
* [Amazon link](https://www.amazon.com/Introduction-Statistical-Learning-Applications-Statistics/dp/1461471370)

**Please, check the `ml_map.png` figure, which is a cheat sheet that helps you to decide which Machine Learning process and category to follow based on your data!**

### Importing ML Library

In [1]:
from sklearn.linear_model import LinearRegression

### Creating the model

In [2]:
model = LinearRegression(normalize=True)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


### Train / Test Split

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [5]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
list(y)

[0, 1, 2, 3, 4]

In [7]:
# splitting data to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
X_train

array([[6, 7],
       [2, 3],
       [4, 5]])

In [9]:
y_train

[3, 1, 2]

In [10]:
X_test

array([[0, 1],
       [8, 9]])

In [11]:
y_test

[0, 4]

### Training the model

In [12]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

### Get predicted values

In [13]:
predictions = model.predict(X_test)

In [14]:
predictions

array([3.60822483e-16, 4.00000000e+00])

In [15]:
model.score(X_test, y_test)

1.0